// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./../components/Counter.vue')['default']
    DropdownCard: typeof import('./../components/DropdownCard/DropdownCard.vue')['default']
    DropdownLink: typeof import('./../components/DropdownCard/DropdownLink.vue')['default']
    DropdownMenuFooter: typeof import('./../components/DropdownCard/DropdownMenuFooter.vue')['default']
    DropdownMenuHeader: typeof import('./../components/DropdownCard/DropdownMenuHeader.vue')['default']
    DropdownMenuItem: typeof import('./../components/DropdownCard/DropdownMenuItem.vue')['default']
    FlowChart: typeof import('./../components/FlowChart/index.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    FormComponentsRender: typeof import('./../components/Form/FormComponentsRender/index.vue')['default']
    FormFooter: typeof import('./../components/Form/FormFooter/index.vue')['default']
    FormItemSet: typeof import('./../components/Form/FormItemSet/index.vue')['default']
    GenPubKeyButton: typeof import('./../components/GenPubKeyButton/index.vue')['default']
    ProCard: typeof import('./../components/ProCard/index.vue')['default']
    ProCardItem: typeof import('./../components/ProCard/ProCardItem.vue')['default']
    ProDialog: typeof import('./../components/ProDialog/index.vue')['default']
    ProTableColumn: typeof import('./../components/ProTable/ProTableColumn.vue')['default']
    ProTableFilters: typeof import('./../components/ProTable/ProTableFilters.vue')['default']
    ProTableTools: typeof import('./../components/ProTable/ProTableTools.vue')['default']
    README: typeof import('./../components/README.md')['default']
    SearchPopover: typeof import('./../components/SearchPopover/index.vue')['default']
    StateTag: typeof import('./../components/StateTag/index.vue')['default']
    Table: typeof import('./../components/ProTable/Table.vue')['default']
    TimeDisplay: typeof import('./../components/TimeDisplay/index.vue')['default']
    TimeLinePicker: typeof import('./../components/TimeLinePicker/index.vue')['default']
  }
}

export { }
